### PR TITLE
preferences-dialog: Port to libadwaita widgetry

### PR DESCRIPTION
**Pull request by jannuary**
Ports the preferences-dialog to libadwaita's Preferences* widgets, putting it in line with the common GNOME preferences pattern.
image
image

Notes:
- This requires a prerelease version of libadwaita due to EntryRow, so it cant be released on Flathub before GNOME 43. (at least without bundling libadwaita)
- This saves settings as the window closes. This isn't ideal - the standard is instant apply.
- ~~Plugins tab hasn't been ported over yet.~~
- ~~Plugins are now trashed instead of being deleted. I need to figure out how to show a notification allowing to untrash it, as well as handle possible errors.~~ This has been reverted since - I don't know what would be a good way to implement it.
- This ignores CSD being disabled. Unsure how supported that case is with PreferencesWindow anyway.
- There's a lot of warnings about mismatched types.
- Last but not least, I'd like to revisit and reorganise the settings design-wise. A lot of these seem either poorly explained or simply not needed.

### CODE REVIEW

**Review by gnome-mpv — CHANGES_REQUESTED** [review]
This looks awesome. Thanks!

There are a few issues that show up during my testing:

1. I'm getting warnings in my console when the preferences dialog is opened.
```
(io.github.celluloid_player.Celluloid:14866): GLib-GObject-WARNING **: 00:13:17.171: ../glib/gobject/gsignal.c:2620: signal 'file-set' is invalid for instance '0x556ab4c20270' of type 'AdwActionRow'

(io.github.celluloid_player.Celluloid:14866): GLib-GObject-WARNING **: 00:13:17.182: ../glib/gobject/gsignal.c:2620: signal 'file-set' is invalid for instance '0x556ab4c208d0' of type 'AdwActionRow'

(io.github.celluloid_player.Celluloid:14866): GLib-GObject-WARNING **: 00:13:17.208: ../glib/gobject/gsignal.c:2620: signal 'response' is invalid for instance '0x556ab4b38360' of type 'CelluloidPreferencesDialog'
```
2. There are compiler warnings about incompatible pointer types. These can be silenced with explicit casts.
3. Changes to plugins and `Extra mpv options` do not take effect until Celluloid is restarted. I think it's because `AdwPreferencesWindow` doesn't have a `response` signal so `CelluloidView` is never notified when it's closed.

**Comment by bertini97** [comment]
Here are two patches that build upon the work from @jannuary : they are in `.txt` as github won't allow me to post `.patch` for some reason: 
1. [0001-fixed-gtk-compiler-warnings-by-explicit-cast.txt](https://github.com/celluloid-player/celluloid/files/11523403/0001-fixed-gtk-compiler-warnings-by-explicit-cast.txt) fixes all compiler warnings by explicit casting, I changed type when appropriate and fixed indentation
2. [0002-preferences-get-updated-upon-window-close-fixed-brok.txt](https://github.com/celluloid-player/celluloid/files/11523404/0002-preferences-get-updated-upon-window-close-fixed-brok.txt) changes the signal required to update the preferences to the preference window close signal (we don't have save and cancel anymore), getting rid of the last GObject warning. It also gets rid of the first two by connecting the signal to the proper emitter. This makes it so the settings are updated mid-execution again as requested.

A couple things: I have tried fixing indentation here and there, but it seems to be 8 spaces long. Also `GtkDialog` is deprecated and replaced by `AdwWindow`: `AdwMessageDialog`, `AdwAlertDialog`, `AdwPreferencesWindow`, etc. The latter doesn't accept the `response` signal. So far this is the only window to transition, so I left the response handler as is, to match the others, but it's receiving a `close-request`, so it's different from all the others.

All other libadwaita programs seem to have an `AdwPreferencesWindow` without a save button, and it might be that they save the settings individually upon change (given that theme changes happen real-time, looking at GNOME's TextEditor). We are instead saving everything on window close.

Let me know what you think, I would love to see this landed.

**Comment by gnome-mpv** [comment]
@bertini97 Thanks for the patches!

> All other libadwaita programs seem to have an AdwPreferencesWindow without a save button, and it might be that they save the settings individually upon change (given that theme changes happen real-time, looking at GNOME's TextEditor). We are instead saving everything on window close.

The reason we're doing that is because some settings require restarting mpv. If the user is playing something, that will interrupt playback which can be pretty annoying.

**Comment by gnome-mpv** [comment]
I made a couple more edits and merged as ed9ba581719fa05304c01fe3b8accf3af7ee2d07 and 2856d74fa3c646e6b53c3a960456213c1dcdb9ab.

**Pull request closed without merging**
