### PR TITLE
Use floating headerbar

### PR DESCRIPTION
**Pull request by AbrarSL**
This change simply reveals the headerbar used for fullscreen mode when in windowed mode too.

image

image

### CODE REVIEW

**Review by gnome-mpv — CHANGES_REQUESTED** [review]
Hi @AbrarSL,

Thanks for the PR. The code looks fine overall, but can you make this an option rather than the default? This is an uncommon UI pattern, so I think it makes sense to have the users opt-in. Also, I think the implementation in your [`floating-header`](https://github.com/AbrarSL/celluloid/tree/floating-header) branch looks better because there is a better balance between the header bar and the controls on the bottom. Can we switch to that one?

**Comment by AbrarSL** [comment]
> Hi @AbrarSL,
> 
> Thanks for the PR. The code looks fine overall, but can you make this an option rather than the default? This is an uncommon UI pattern, so I think it makes sense to have the users opt-in. Also, I think the implementation in your [`floating-header`](https://github.com/AbrarSL/celluloid/tree/floating-header) branch looks better because there is a better balance between the header bar and the controls on the bottom. Can we switch to that one?

I've attempted to implement this as an option. I've also adopted a similar style to the one in that branch. A couple of things to note.
- For obvious reasons the app always hides the floating headerbar when csd is disabled.
- The floating headerbar style is always applied to the video headerbar, that means the fullscreen header now always uses the floating style.
- The floating preference requires an app restart. Making the preference work without a restart would've required some more careful code and I'm not really familiar with C. There's also the fact that this setting is influenced by the csd option which also requires a restart so I hope that's okay.

Screenshot from 2024-01-15 11-16-12
image

**Review by gnome-mpv — CHANGES_REQUESTED** [review]
Thanks. This is almost ready, but I noticed that the option doesn't take effect immediately after you toggle it; you have to restart Celluloid for the change to take effect. If you make `always-use-floating-headerbar` a property, you can bind it to the GSettings key and all changes will take effect immediately. For an example, you can take a look at how `always-use-floating-controls` is bound in CelluloidApplication.

**Comment by AbrarSL** [comment]
I tried to make a reproducer but that works fine. I suspect the issue is caused by the initial size allocation. It's a gut feeling though, I'm not sure where to proceed from here. Would appreciate some further guidance @gnome-mpv

**Comment by gnome-mpv** [comment]
Based on my testing, the header is brought back because mpv has the `border` property set to `on` by default. So when mpv finishes initializing, our handler for `border` fires, sees that it's set to `on`, and made the header bar visible. To fix this, we'll probably have to drop support for the `border` property, but I don't think many (if any) people are using it, so that might be okay. I can work on that later.

**Comment by AbrarSL** [comment]
> Based on my testing, the header is brought back because mpv has the `border` property set to `on` by default. So when mpv finishes initializing, our handler for `border` fires, sees that it's set to `on`, and made the header bar visible. To fix this, we'll probably have to drop support for the `border` property, but I don't think many (if any) people are using it, so that might be okay. I can work on that later.

Great. Can this be merged then?

**Comment by AbrarSL** [comment]
Simply deleting the code that sets the titlebar visibility for the border property works well enough. I'll do that. I'll let the property and the decoration stuff be though. Being able to disable window shadows could be a nice performance boost for people with slower machines.

**Comment by gnome-mpv** [comment]
I found another problem. When the window is unfocused, the header bar turns opaque. I think it's the CSS rules that comes with GTK that's doing this. We need to figure out how to stop them from taking effect in floating mode somehow.

**Comment by AbrarSL** [comment]
> I found another problem. When the window is unfocused, the header bar turns opaque. I think it's the CSS rules that comes with GTK that's doing this. We need to figure out how to stop them from taking effect in floating mode somehow.

This seems to be a known issue https://github.com/celluloid-player/celluloid/pull/919#issuecomment-1897798450

**Comment by AbrarSL** [comment]
Delfin has a workaround. https://codeberg.org/avery42/delfin/src/commit/e32cb274727f0cbc6fdfaf38a1824d8f4bde3929/delfin/src/styles/video-player.scss#L7

I guess I could just set the background to this manually.

**Comment by AbrarSL** [comment]
I decided to split the commits out in a way that seems to match what's usually done in this repo. Tell me if the previous commits were better and I can restore them. I also fixed the headerbar color issue by setting the background for the headerbar whenever floating mode is used.

**Comment by gnome-mpv** [comment]
I decided to remove the `border` property anyway. I think it would be confusing if it doesn't work the way it does in mpv.

PR merged as a99d1e3bcab5e4dca11d5f175d48b2d858ee5573, 136c26f89247d5e9938eff91a94c7e92fe9cca2a, 99abbfb56e431e5951b6d3955ee134fdd2e363e5, 8ad0148a6d227c1f59b719b1e17eeed81edb21f3, and 3e32e212d712cbdb1747a7c73d7a78457449abd4. Thanks for contributing!

**Pull request closed without merging**
