### PR TITLE
Reduce required gettext version to 0.19

### PR DESCRIPTION
**Pull request by mymedia2**
This seems to work okay with no any modifications. This makes possible to build the application against gettext available even in Debian oldoldstable. We have already this patch for the [celluloid][1] package, and it may be useful for others.

 [1]: https://sources.debian.org/src/celluloid/0.18-2/debian/patches/relax-gettext-version.patch/

### CODE REVIEW

**Comment by gnome-mpv** [comment]
On my machine (gettext 0.21), this patch makes build fail with this error message:
```*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20```

**Comment by mymedia2** [comment]
@gnome-mpv I daresay you should clean working directory before, and refresh the `po/Makefile.in.in` file that is auto-generated and points to previously configured gettext.

**Comment by gnome-mpv** [comment]
@mymedia2 That was with a freshly cloned repo.

**Comment by mymedia2** [comment]
@gnome-mpv to be honest, I can't reproduce your issue, even though I have installed gettext 0.21 compiled from source. Which command produces that error?

**Comment by gnome-mpv** [comment]
@mymedia2 
>Which command produces that error?

I ran `./autogen.sh` then `make`.

**Comment by mymedia2** [comment]
Ok, I have managed to reproduce the issue. It appears the AM_GNU_GETTEXT_VERSION macro points to exact gettext version that should be installed on a system where celluloid builds. This is inconvenient a bit for porting. There is the AM_GNU_GETTEXT_REQUIRE_VERSION macro which declares _minimum_ required gettext version. It is allowed to use at least one of them, however autoreconf does not recognize the second one. (A [patch][1] was sent to Autotools maintainers, yet still unapplied). So we have two options here.

1. Place both of the macros to the configure.ac file. So the autoreconf script will invoke the autopoint utility. The latter, in its turn, will [ignore][2] simple AM_GNU_GETTEXT_VERSION.

2. On the other hand, it is possible to leave in configure.ac only AM_GNU_GETTEXT_REQUIRE_VERSION and add a separate call of autopoint to the autogen.sh wrapper.

 [1]: https://lists.gnu.org/archive/html/autoconf-patches/2015-10/msg00000.html
 [2]: https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/misc/autopoint.in;h=3a24eee5d014524da9770fbf7577d601a2c72458;hb=HEAD#l336

**Comment by gnome-mpv** [comment]
Thank you for looking into this. I modified the patch to include AM_GNU_GETTEXT_REQUIRE_VERSION (option 1) and merged as a5de3781c9305e1f43778e51737a4cdb744669af.

**Pull request closed without merging**
