### PR TITLE
Redesign controls

### PR DESCRIPTION
**Pull request by jannuary**
Redesigns the controls, as per #696. There's still stuff to do to close that issue, but it's already pretty good :) 

- Also adds adaptivity via AdwBreakpoint and kills old compact mode – this bumps the libadwaita dependency to 1.4.
- ~~Removes~~ Pushes duplicated ControlBox and HeaderBar in MainWindow under the rug – the same ones are used whether in floating mode or not. Ideally, those should be deleted, but it seems a lot of things depend on them and GtkWindow gives you a titlebar if you don't have a HeaderBar set as one.
- Controls now don't fade out when playback is paused.
- It isn't obvious where to drag the window in floating mode when "Make video area draggable" is off.
- 🔁, 🔀, ⏹️ and ⤢ have been deleted from the control box. Loop and shuffle concern the playlist and thus would move to the playlist UI, fullscreen is already in the header bar and stop will be gone forever.
- Possibly missing something else?

image
image
image
image

### CODE REVIEW

**Comment by gnome-mpv** [comment]
> It isn't obvious where to drag the window in floating mode when "Make video area draggable" is off.

It's probably okay to just remove the option and keep the video draggable at all times.

**Review by gnome-mpv — CHANGES_REQUESTED** [review]
Here's a few issues I found from my testing:
- There's a crash that happens whenever you click the volume button.
- If you launch Celluloid without opening a file, the controls will be hidden until you move your mouse over the window.
- If you pause the video while the controls are hidden (e.g. with media keys), it stays hidden.
- There's a similar issue when you exit fullscreen with non-floating controls. The controls stays hidden until you move your mouse over the the window.

**Comment by jannuary** [comment]
> It's probably okay to just remove the option and keep the video draggable at all times.

I think it would be fine to enable draggable-video-area-enable if and only if always-use-floating-controls is used, since you can just drag from header bar otherwise.

> There's a crash that happens whenever you click the volume button.

I'm puzzled by that. I haven't messed around with the volume button, and unless I'm missing something obvious, I'm not sure what would introduce a crash. I unbound popup:visible from control-box:volume-popup-visible and that seems to have fixed it – but again, no clue what caused it and why it worked in master – it seems to complain about the popover not being inside of a toplevel.

**Review by gnome-mpv — CHANGES_REQUESTED** [review]
I found another problem in non-floating mode. The header bar is being overlaid on top of the video, so the top of the video will get covered if the window isn't tall enough.

**Comment by jannuary** [comment]
>  The header bar is being overlaid on top of the video, so the top of the video will get covered if the window isn't tall enough.

Fixed! It completely went over my head how one of the sizing functions queries video_area (which　is *larger* than the video when the controls are docked), which resulted in the video having an incorrect size and mpv being pushed up and cropped (somehow) 
image

**Comment by jannuary** [comment]
I'm fairly sure this fixes the last remaining issues wrt non-floating and non-csd modes.

**Comment by gnome-mpv** [comment]
Merged as 5e961df9b3d441fa46263f0380ae1db84a67f6cd.

I made some small adjustments to the CSS because it's using some variables that were only added in libadwaita 1.6 which is still in beta. We can change it back once 1.6 is released

**Comment by jannuary** [comment]
> I made some small adjustments to the CSS because it's using some variables that were only added in libadwaita 1.6 which is still in beta. We can change it back once 1.6 is released

That's fair enough, though the video-area's background really should've been changed to @view_bg_color instead — light mode is broken otherwise and the controls have poor contrast.

**Comment by gnome-mpv** [comment]
> That's fair enough, though the video-area's background really should've been changed to @view_bg_color instead — light mode is broken otherwise and the controls have poor contrast.

Makes sense. I've changed it to `@view_bg_color` in db83f1eb959202046a114d337416e119a0ab71ca.

**Pull request closed without merging**
