### PR TITLE
italian translation updated

### PR DESCRIPTION
**Pull request by loropo9043**
sorry but i lost my zanata credential and nobody added me to italian group in order to translate this app on zanata....

### CODE REVIEW

**Comment by gnome-mpv** [comment]
Merged as efc41d3ef0ba819480c22182bb6acacd2480652e.

**Comment by gnome-mpv** [comment]
>sorry but i lost my zanata credential and nobody added me to italian group in order to translate this app on zanata....

What's your username on Zanata? I can add you to the project directly.

**Comment by loropo9043** [comment]
lucatrevisani90

**Comment by gnome-mpv** [comment]
Added. You should be able to translate now.

**Pull request closed without merging**
