### PR TITLE
Use Libadwaita 

### PR DESCRIPTION
**Pull request by jannuary**
Gives us the new stylesheet as well as (eventually) [proper dark style API. ](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference)

TODO: 

- [x] Use `AdwStyleManager` instead of `GtkSettings:gtk-application-prefer-dark-theme` - otherwise it appears broken. 
- [x] Deal with system-wide preference somehow 
- [x] Cleanup stuff

### CODE REVIEW

**Comment by TheOPtimal** [comment]
Quick question, why is the preferences window not AdwPreferences, and rather is a notebookbar-style one?

**Comment by jannuary** [comment]
> Quick question, why is the preferences window not AdwPreferences, and rather is a notebookbar-style one?

Because this is not in scope for this particular PR.

**Comment by gnome-mpv** [comment]
Just a quick update. I think this is basically ready to merge now, but the latest release has been buggier than I anticipated. I plan to make another release to fix the more serious bugs and merge this PR after that.

**Comment by gsantner** [comment]
Can you please consider to have an option (doesn't matter, any of ENV/UI/CLI-flag), to disable this  (I.e. the enforced adwaita theme)?

I would like to continue to use Celluloid/Gnome-MPV with Numix, without the need to patch it :smile: .

grafik

**Comment by gnome-mpv** [comment]
>Can you please consider to have an option (doesn't matter, any of ENV/UI/CLI-flag), to disable this (I.e. the enforced adwaita theme)?

You will still be able to override the theme using the `GTK_THEME` env var.

**Comment by gnome-mpv** [comment]
Merged as:
6127e387bf48153e6782353b8a10a68cc75b1c54
c38e6a5519e2fc10898ea65afa6fcbda624845ee
9c6a5f73cc9b47b00bd9b0c2fbee55f7b483a515
8648c8aa95c54208c8ec83f5d9f131400a71a43b

Thanks for the PR!

**Pull request closed without merging**
